# configs/lgbm_search.yaml
    
# =================================================================
# 0. ОБЩИЕ ПАРАМЕТРЫ
# =================================================================
mode: "search"

experiment_name: "Default LGBM Search"

common_params:
  asset_name: "EURUSD_D"
  model_type: "lightgbm"
  differencing: "auto"
  column_mapping:
    0: "Date"
    1: "Time"
    2: "Open"
    3: "High"
    4: "Low"
    5: "Close"
    6: "Volume"
  task_type: "regression"
  targets: ["High", "Low"]
  # labeling_horizon будет перебираться в search_mode,
  # но можно задать значение по умолчанию для других режимов.
  labeling_horizon: 20

# =================================================================
# 1. НАСТРОЙКИ ДЛЯ РЕЖИМА ПОИСКА (mode: "search")
# =================================================================
search_mode:
  log_history_per_epoch: false # Управление логированием
  n_trials: 100 # Значение по умолчанию для поиска
  space:
    feature_set_name:
      type: categorical
      choices: ["base_indicators", "ohlcv_with_rsi"]
    labeling_horizon: {type: int, low: 5, high: 20}
    # Параметры LightGBM
    model_params:
      n_estimators:
        {type: int, low: 50, high: 250}
      num_leaves:
        {type: int, low: 20, high: 50}
    train_params:
      learning_rate:
        {type: float, low: 0.01, high: 0.2, log: true}

# =================================================================
# 2. НАСТРОЙКИ ДЛЯ РЕЖИМА ОБУЧЕНИЯ (mode: "train")
# =================================================================
train_mode:
  log_history_per_epoch: true
  model_params:
    n_estimators:
    num_leaves:

  train_params:
    learning_rate: 

# =================================================================
# 3. НАСТРОЙКИ ДЛЯ РЕЖИМА ДООБУЧЕНИЯ (mode: "finetune")
# =================================================================
finetune_mode:
  log_history_per_epoch: true
  source_run_id: null
  train_params:
    learning_rate: 
