# configs/lgbm_search.yaml
    
# =================================================================
# 0. ОБЩИЕ ПАРАМЕТРЫ
# =================================================================
mode: "search" # search / train / finetune

# Имя эксперимента для MLflow
experiment_name: "Default LGBM Search"

common_params:
  asset_name: "EURUSD_D"
  model_type: "lightgbm"
  feature_set_name: "base_indicators"
  differencing: "auto"
  column_mapping:
    0: "Date"
    1: "Time"
    2: "Open"
    3: "High"
    4: "Low"
    5: "Close"
    6: "Volume"
  task_type: "regression"
  targets: ["High", "Low"] #  ["High", "Low"] / ["Close"]
  # labeling_horizon будет перебираться в search_mode,
  # но можно задать значение по умолчанию для других режимов.
  labeling_horizon: 20

  # Объединять Train+Validation для "плоских" моделей
  train_on_full_data: true

  # --- Параметры для генерации лаговых признаков ---
  # Ключ - имя колонки, значение - список периодов для сдвига
  lag_features:
    # High: [1, 2]
    # Low: [1, 2]
    Open: [1, 2]
    Close: [1, 2]
    #Volume: [1, 2, 3]

  enrichment_data:
    - filename: "BANK RATE EUR.csv"
      data_type: "interest_rate"
    - filename: "BANK RATE USD.csv"
      data_type: "interest_rate"
    - filename: "CPI_EUR.csv"
      data_type: "cpi"
    - filename: "CPI_USA.csv"
      data_type: "cpi"
  
  visualization_params:
    # Список данных для отображения на графике.
    # Для каждого файла указывается список конкретных колонок.
    plot_enrichment_data:
    #  - filename: "BANK RATE EUR"
    #    columns: ["rate"]
      - filename: "BANK RATE USD"
        columns: ["rate"]
      - filename: "CPI_USA"
        columns: ["cpi", "cpi_Fore"] # Можно указать несколько, например ["cpi", "cpi_Fore"]
    #  - filename: "CPI_EUR"
    #    columns: ["cpi", "cpi_Fore"]
# =================================================================
# 1. НАСТРОЙКИ ДЛЯ РЕЖИМА ПОИСКА (mode: "search")
# =================================================================
search_mode:
  log_history_per_epoch: false # Управление логированием
  n_trials: 50 # Значение по умолчанию для поиска
  space:
    feature_set_name:
      type: categorical
      choices: ["base_indicators", "ohlcv_with_rsi"]
    labeling_horizon: {type: int, low: 5, high: 20}
    # Параметры LightGBM
    model_params:
      n_estimators:
        {type: int, low: 50, high: 150}
      num_leaves:
        {type: int, low: 20, high: 50}
    train_params:
      learning_rate:
        {type: float, low: 0.01, high: 0.2, log: true}

# =================================================================
# 2. НАСТРОЙКИ ДЛЯ РЕЖИМА ОБУЧЕНИЯ (mode: "train")
# =================================================================
train_mode:
  log_history_per_epoch: true
  model_params:
    n_estimators: 110
    num_leaves: 23

  train_params:
    learning_rate: 0.027599717522677192

# =================================================================
# 3. НАСТРОЙКИ ДЛЯ РЕЖИМА ДООБУЧЕНИЯ (mode: "finetune")
# =================================================================
finetune_mode:
  log_history_per_epoch: true
  source_run_id: null
  train_params:
    learning_rate: 
