# configs/lstm_hard_mode.yaml

# =================================================================
# 0. ОБЩИЕ ПАРАМЕТРЫ
# =================================================================
mode: "search" # search / train / finetune

# Имя эксперимента для MLflow
experiment_name: "LSTM Hard Mode Training"

common_params:
  asset_name: "EURUSD_D"
  model_type: "lstm"
  feature_set_name: "keras_custom"
  differencing: "auto"
  column_mapping:
    0: "Date"
    1: "Time"
    2: "Open"
    3: "High"
    4: "Low"
    5: "Close"
    6: "Volume"
  task_type: "regression"
  targets: ["Close"] # ["Close"] / ["High", "Low"]
  labeling_horizon: 20
  x_len: 22
  
  enrichment_data:
    - filename: "BANK RATE EUR.csv"
      data_type: "interest_rate"
    - filename: "BANK RATE USD.csv"
      data_type: "interest_rate"
    - filename: "CPI_EUR.csv"
      data_type: "cpi"
    - filename: "CPI_USA.csv"
      data_type: "cpi"
  
  visualization_params:
    # Список данных для отображения на графике.
    # Для каждого файла указывается список конкретных колонок.
    plot_enrichment_data:
      - filename: "BANK RATE EUR"
        columns: ["rate"]
      - filename: "BANK RATE USD"
        columns: ["rate"]
      - filename: "CPI_USA"
        columns: ["cpi", "cpi_Fore"] # Можно указать несколько, например ["cpi", "cpi_Fore"]
      - filename: "CPI_EUR"
        columns: ["cpi", "cpi_Fore"]
  
# =================================================================
# 1. НАСТРОЙКИ ДЛЯ РЕЖИМА ПОИСКА (mode: "search")
# =================================================================
search_mode:
  # НЕПЕРЕБИРАЕМЫЕ при помощи Optuna параметры
  log_history_per_epoch: false # Управление логированием
  n_trials: 5
  # --- Параметры целевой функции Optuna ---
  objective_metric: "sharpe_ratio" # mse / sharpe_ratio
  objective_direction: "maximize" # minimize / maximize
  # --- Параметр targets модели ---
  model_params:
    out_units: 1 # 1 / 2 
  train_params:
    early_stopping_monitor: 'val_loss'
  
  # ПЕРЕБИРАЕМЫЕ при помощи Optuna параметры
  space:
    # --- Общие параметры ---
    feature_set_name:
      type: categorical
      choices: [
        "keras_custom",
        "base_indicators",
        "ohlcv_with_rsi",
        "ohlcv_with_stochastic",
        "ohlcv_with_macd",
        "ohlcv_with_obv"      
      ]
    labeling_horizon: {type: int, low: 10, high: 30}
    x_len: {type: int, low: 10, high: 40}

    # --- Параметры архитектуры модели ---
    model_params:
      lstm_units_1: {type: int, low: 16, high: 256}
      lstm_units_2: {type: int, low: 16, high: 256}
      dropout_rate_1: {type: float, low: 0.1, high: 0.5}
      dropout_rate_2: {type: float, low: 0.1, high: 0.5}

    # --- Параметры процесса обучения ---
    train_params:
      learning_rate: {type: float, low: 0.0001, high: 0.01, log: true}
      epochs: {type: categorical, choices: [10, 15]}
      early_stopping_patience: {type: int, low: 15, high: 50}

# =================================================================
# 2. НАСТРОЙКИ ДЛЯ РЕЖИМА ОБУЧЕНИЯ (mode: "train")
# =================================================================
train_mode:
  log_history_per_epoch: true # Управление логированием
  model_params:
    lstm_units_1: 32
    lstm_units_2: 190
    dropout_rate_1: 0.11133448644957677
    dropout_rate_2: 0.31276907649732033
    out_units: 2
  train_params:
    epochs: 200
    learning_rate: 0.003908599821415534
    early_stopping_patience: 50
    early_stopping_monitor: 'val_loss'

# =================================================================
# 3. НАСТРОЙКИ ДЛЯ РЕЖИМА ДООБУЧЕНИЯ (mode: "finetune")
# =================================================================
finetune_mode:
  log_history_per_epoch: true # Управление логированием
  source_run_id: 4f044925f6934b0a88a0ab58af62d0fb
  train_params:
    learning_rate: 0.00001
    epochs: 100
    early_stopping_patience: 20
    early_stopping_monitor: 'val_loss'