# configs/lstm_hard_mode.yaml

# Имя эксперимента для MLflow
experiment_name: "LSTM Hard Mode Training"

# --- Все параметры теперь "заморожены" ---
asset_name: "EURUSD_D"
model_type: "lstm"
task_type: "regression"
feature_set_name: "base_indicators"
labeling_horizon: 14

# Карта колонок
column_mapping:
  0: "Date"
  1: "Time"
  2: "Open"
  3: "High"
  4: "Low"
  5: "Close"
  6: "Volume"

# --- Секция для дообучения
finetune_from_run:
  # Оставьте "run_id" пустым (или null) для режима поиска/первого обучения
  # Заполните "run_id" значением Run ID () лучшего run'а модели из MLflow
  run_id: null

# --- Управление логированием (отключаем для режима поиска/включаем для режима (до)обучения) ---
log_history_per_epoch: true

# Параметры модели, взятые из лучшего trial
model_params:
  lstm_units: 102
  dropout_rate: 0.491490012836181

train_params:
  epochs: 200
  learning_rate: 0.00026314286878353633
  early_stopping_patience: 20
  early_stopping_monitor: 'val_loss'

# --- Секция для перебора Optuna ---
# (не используется при заполненном "finetune_from_run.run_id") ---
search_space: {}