# configs/lstm_hard_mode.yaml

# =================================================================
# 0. ОБЩИЕ ПАРАМЕТРЫ
# =================================================================
mode: "train"

experiment_name: "LSTM Hard Mode Training"

common_params:
  asset_name: "EURUSD_D"
  model_type: "lstm"
  feature_set_name: "base_indicators"
  column_mapping:
    0: "Date"
    1: "Time"
    2: "Open"
    3: "High"
    4: "Low"
    5: "Close"
    6: "Volume"
  task_type: "regression"
  targets: ["High", "Low"]
  labeling_horizon: 20

# =================================================================
# 1. НАСТРОЙКИ ДЛЯ РЕЖИМА ПОИСКА (mode: "search")
# =================================================================
search_mode:
  log_history_per_epoch: false # Управление логированием
  n_trials: 0
  space: {}

# =================================================================
# 2. НАСТРОЙКИ ДЛЯ РЕЖИМА ОБУЧЕНИЯ (mode: "train")
# =================================================================
train_mode:
  log_history_per_epoch: true # Управление логированием
  model_params:
    lstm_units_1: 83
    lstm_units_2: 42
    dropout_rate_1: 0.26706022765276477
    dropout_rate_2: 0.26706022765276477
    out_units: 2
  train_params:
    epochs: 20
    learning_rate: 0.004218676180451373
    early_stopping_patience: 20
    early_stopping_monitor: 'val_loss'

# =================================================================
# 3. НАСТРОЙКИ ДЛЯ РЕЖИМА ДООБУЧЕНИЯ (mode: "finetune")
# =================================================================
finetune_mode:
  log_history_per_epoch: true # Управление логированием
  source_run_id: null
  train_params:
    learning_rate: 0.00001
    epochs: 100
    early_stopping_patience: 20
    early_stopping_monitor: 'val_loss'