# configs/lstm_hard_mode_2.yaml

# =================================================================
# 0. ОБЩИЕ ПАРАМЕТРЫ
# =================================================================
mode: "search" # search / train / finetune

# Имя эксперимента для MLflow
experiment_name: "LSTM Hard Mode Training"

common_params:
  asset_name: "EURUSD_D"
  model_type: "lstm_v2"
  feature_set_name: "HiLo"
  differencing: "auto"
  column_mapping:
    0: "Date"
    1: "Time"
    2: "Open"
    3: "High"
    4: "Low"
    5: "Close"
    6: "Volume"
  task_type: "regression"
  targets: ["High", "Low"] # ["Close"] / ["High", "Low"]
  labeling_horizon: 2
  x_len: 22

# =================================================================
# 1. НАСТРОЙКИ ДЛЯ РЕЖИМА ПОИСКА (mode: "search")
# =================================================================
search_mode:
  # НЕПЕРЕБИРАЕМЫЕ при помощи Optuna параметры
  log_history_per_epoch: false # Управление логированием
  n_trials: 100
  # --- Параметры целевой функции Optuna ---
  objective_metric: "sharpe_ratio" # mse / sharpe_ratio
  objective_direction: "maximize" # minimize / maximize
  # --- Параметр targets модели ---
  model_params:
    out_units: 2 # 1 / 2 
  train_params:
    early_stopping_monitor: 'val_loss'

  # ПЕРЕБИРАЕМЫЕ при помощи Optuna параметры
  space:
    # --- Общие параметры ---
    feature_set_name:
      type: categorical
      choices: ["ohlcv"]
    labeling_horizon: {type: int, low: 1, high: 5}
    x_len: {type: int, low: 10, high: 40}
    
    # --- Параметры архитектуры модели ---
    model_params:
      lstm_units_1: {type: int, low: 16, high: 128}
      lstm_units_2: {type: int, low: 16, high: 128}
      lstm_units_3: {type: int, low: 16, high: 128}
      lstm_units_4: {type: int, low: 16, high: 128}
      dropout_rate_1: {type: float, low: 0.1, high: 0.5}
      dropout_rate_2: {type: float, low: 0.1, high: 0.5}
      dropout_rate_3: {type: float, low: 0.1, high: 0.5}
      dropout_rate_4: {type: float, low: 0.1, high: 0.5}
    
    # --- Параметры процесса обучения ---
    train_params:
      learning_rate: {type: float, low: 0.0001, high: 0.01, log: true}
      epochs: {type: categorical, choices: [50, 100]}
      #early_stopping_patience: {type: int, low: 10, high: 25}

# =================================================================
# 2. НАСТРОЙКИ ДЛЯ РЕЖИМА ОБУЧЕНИЯ (mode: "train")
# =================================================================
train_mode:
  log_history_per_epoch: true # Управление логированием
  model_params:
    lstm_units_1: 83
    lstm_units_2: 42
    dropout_rate_1: 0.29
    dropout_rate_2: 0.29
    out_units: 2
  train_params:
    epochs: 200
    learning_rate: 0.004
    early_stopping_patience: 50
    early_stopping_monitor: 'val_loss'

# =================================================================
# 3. НАСТРОЙКИ ДЛЯ РЕЖИМА ДООБУЧЕНИЯ (mode: "finetune")
# =================================================================
finetune_mode:
  log_history_per_epoch: true # Управление логированием
  source_run_id: null
  train_params:
    learning_rate: 0.00001
    epochs: 100
    early_stopping_patience: 20
    early_stopping_monitor: 'val_loss'