# Имя эксперимента для MLflow
experiment_name: "Stress Test - Large Feature Set"

# --- "Замороженные" параметры ---
asset_name: "EURUSD_D"
model_type: "lightgbm"
task_type: "regression"

# Карта для файла без заголовка
column_mapping:
  0: "Date"
  1: "Time"
  2: "Open"
  3: "High"
  4: "Low"
  5: "Close"
  6: "Volume"
    
# --- Секция для перебора Optuna ---
search_space:
  # Используем только один, но очень большой набор признаков
  feature_set_name:
    type: categorical
    choices: ["stress_test_features"]
  
  labeling_horizon:
    type: int
    low: 30 # Увеличим горизонт, так как некоторые индикаторы требуют длинной истории
    high: 40

  # Вложенные параметры модели (оставим для полноты картины)
  model_params:
    n_estimators:
      type: int
      low: 50
      high: 100
    
    learning_rate:
      type: float
      low: 0.05
      high: 0.1
      log: true
