    
# Имя эксперимента для MLflow
experiment_name: "Test Search EURUSD LightGBM"

# --- "Замороженные" параметры ---
asset_name: "EURUSD_D"
model_type: "lightgbm"

# --- Секция для перебора Optuna ---
search_space:
  # Параметры предобработки
  feature_set_name:
    type: categorical
    choices: ["base_indicators", "ohlcv_with_rsi"]
  
  labeling_horizon:
    type: int
    low: 5
    high: 10 # Уменьшим диапазон для быстрого теста

  # Вложенные параметры модели
  model_params:
    n_estimators:
      type: int
      low: 50
      high: 150
    
    learning_rate:
      type: float
      low: 0.01
      high: 0.1
      log: true # log=true - хороший выбор для learning_rate
